#!/bin/bash

bold=$(tput bold)
norm=$(tput sgr0)
GREEN='\033[0;32m'
RED='\033[0;31m'
BROWN='\033[0;33m'
NC='\033[0m' # no color

[ $# -ge 1 -a -f "$1" ] && input="$1" || input="-"
raw=$(cat $input)
raw=${raw//http:\/\//}
raw=${raw//https:\/\//}
raw=$(printf "$raw" | xargs -n1 | sort -u | xargs)
IFS=$' ' read -rd '' -a hosts <<<"$raw"

declare -A ips

for host in "${hosts[@]}"; do
	host=$(printf $host | tr -d '\r')
	echo -n -e "${BROWN}[+]${NC} $host"

	if [[ $host != "" ]]; then
		raw_ip=$(dig +short "${host}")

		if [[ $raw_ip != "" ]]; then
			printf "\n"

			IFS=$'\n' read -rd '' -a ip <<<"$raw_ip"
			fip=${ip[-1]}
			isset=${ips[$fip]}

			if [[ $isset != "" ]]; then
				ips[$fip]+=",$host"
			else
				ips[$fip]=$host
			fi
		else
			echo -e " ${RED}${bold}[IP Not Found]${norm}${NC}"
		fi
	fi
done

printf "\nRESULTS:\n"
for ip in "${!ips[@]}"; do
	echo -e "${GREEN}${bold}[+]${NC} $ip${norm}"

	IFS=$',' read -rd '' -a _hosts <<<"${ips[$ip]}"

	for host in "${_hosts[@]}"; do
		printf "\t"
		echo "|_ $host"		
	done
done