#!/bin/bash

bold=$(tput bold)
norm=$(tput sgr0)
GREEN='\033[0;32m'
RED='\033[0;33m'
NC='\033[0m' # no color

[ $# -ge 1 -a -f "$1" ] && input="$1" || input="-"
raw=$(cat $input)
IFS=$'\n' read -rd '' -a hosts <<<"$raw"

declare -A ips

for host in "${hosts[@]}"; do
	echo -e "${RED}[+]${NC} $host"
	raw_ip=$(dig +short "${host[0]}")
	IFS=$'\n' read -rd '' -a ip <<<"$raw_ip"
	fip=${ip[-1]}
	isset=${ips[$fip]}

	if [[ $isset != "" ]]; then
		ips[$fip]+=",$host"
	else
		ips[$fip]=$host
	fi

done

printf "\nRESULTS:\n"
for ip in "${!ips[@]}"; do
	echo -e "${GREEN}${bold}[+]${NC} $ip${norm}"

	IFS=$',' read -rd '' -a _hosts <<<"${ips[$ip]}"

	for host in "${_hosts[@]}"; do
		printf "\t"
		echo "|_ $host"		
	done
done